// backend_angular_react/react_frontend/src/App.tsx
import React, { useState } from 'react';
import logo from './logo.svg';
import './App.css';
import axios from 'axios';
import { useNavigate } from 'react-router-dom';

function App() {
    const [userName, setName] = useState("");
    const [userPass, setPass] = useState("");

    const navigate = useNavigate();

    const myURL = "http://localhost:4000/api/user/checkLogin";

    const makeLogin = () => {
        const data = {
            "user_name": userName,
            "password": userPass
        }

        axios.post(myURL, data)
            .then(response => {
                console.log("inject login.....")
                navigate("http://www.ynet.co.il");
            })
            .catch(err => {
                console.log("oh no .....");
                navigate("https://www.pinterest.com/pin/56224695327525576/");
            });
    }

    return (
        <div style={{ marginTop: 100 }}>

            <div className='Box'>
                <h2>Login Form</h2>
                <input type="text" placeholder='enter user name' onChange={(args) => setName(args.target.value)} /><br /><br />
                <input type="password" placeholder='enter user pass' onChange={(args) => setPass(args.target.value)} /><br /><br />
                <input type="button" value="login" onClick={makeLogin} />
            </div>
        </div>
    );
}

export default App;

// backend_angular_react/angular_frontend/src/app/app.component.ts
import { HttpClient } from '@angular/common/http';
import { Component } from '@angular/core';

@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.css']
})
export class AppComponent {
    title = 'angular_frontend';
    userName = '';
    userPass = '';
    myURL = "http://localhost:4000/api/user/checkLogin";

    constructor(private http: HttpClient) {

    }
    onUserChange(event: any) {
        this.userName = event.target.value;
    }

    onPassChange(event: any) {
        this.userPass = event.target.value;
    }

    onMakeLogin() {
        console.log("user: ", this.userName);
        console.log("pass: ", this.userPass);

        const data = {
            "user_name": this.userName,
            "password": this.userPass
        }

        this.http.post(this.myURL, data).forEach(item => console.log(item));
    }
}

<div class="login">
    <div class='Box'>
        <h2>Login Form</h2>
        <input type="text" placeholder='enter user name' (input)="onUserChange($event)" /><br /><br />
        <input type="password" placeholder='enter user pass' (input)="onPassChange($event)" /><br /><br />
        <input type="button" value="login" (click)="onMakeLogin()" />
    </div>
</div>
